# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(198, 231, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 20, 271, 81))
        self.label.setObjectName("label")
        self.view_login_history_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.view_login_history_button.setGeometry(QtCore.QRect(290, 150, 241, 61))
        self.view_login_history_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.view_login_history_button.setObjectName("view_login_history_button")
        self.manage_materials_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.manage_materials_button.setGeometry(QtCore.QRect(290, 260, 241, 61))
        self.manage_materials_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.manage_materials_button.setObjectName("manage_materials_button")
        self.generate_report_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.generate_report_button.setGeometry(QtCore.QRect(290, 360, 241, 61))
        self.generate_report_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.generate_report_button.setObjectName("generate_report_button")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 460, 241, 61))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Добро пожаловать!</span></p></body></html>"))
        self.view_login_history_button.setText(_translate("MainWindow", "Посмотреть историю входа"))
        self.manage_materials_button.setText(_translate("MainWindow", "Управление расходными материалами"))
        self.generate_report_button.setText(_translate("MainWindow", "Сформировать отчет"))
        self.pushButton_4.setText(_translate("MainWindow", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
