# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(198, 231, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_label.setGeometry(QtCore.QRect(180, 130, 91, 41))
        self.login_label.setObjectName("login_label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 240, 101, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 30, 191, 51))
        self.label_3.setObjectName("label_3")
        self.login_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.login_input.setGeometry(QtCore.QRect(210, 190, 351, 41))
        self.login_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.login_input.setObjectName("login_input")
        self.password_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(210, 300, 351, 41))
        self.password_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_input.setObjectName("password_input")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(570, 310, 141, 21))
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 360, 91, 31))
        self.label.setObjectName("label")
        self.captcha_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.captcha_input.setGeometry(QtCore.QRect(210, 390, 241, 41))
        self.captcha_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.captcha_input.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.captcha_input.setObjectName("captcha_input")
        self.refresh_captcha_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.refresh_captcha_button.setGeometry(QtCore.QRect(60, 480, 201, 41))
        self.refresh_captcha_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.refresh_captcha_button.setObjectName("refresh_captcha_button")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 480, 201, 41))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:14pt; font-weight:600;\">Логин:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:14pt; font-weight:600;\">Пароль:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">Авторизация </span></p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "Показать пароль"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">CAPTCHA:</span></p></body></html>"))
        self.refresh_captcha_button.setText(_translate("MainWindow", "Обновить CAPTCHA"))
        self.pushButton_2.setText(_translate("MainWindow", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
